### ISSUE TITLE
Not connecting to Wireless@SGx after adding credentials

### ISSUE THREAD

**Issue by deearahman** [zerotypic/wasg-register#7]
Hello,

Thank you for this. I've been trying to connect to wireless@sgx.

I'm however unable to connect to Wireless@SGx. It will try to connect to Wireless@SGx and prompt userid and password again, and then reconnect to Wireless@SG.

![Screenshot from 2020-09-24 09-11-57](https://user-images.githubusercontent.com/32949602/94090302-db15e600-fe47-11ea-9240-4dc0783ad18c.png)

![Screenshot from 2020-09-24 09-25-31](https://user-images.githubusercontent.com/32949602/94090602-98a0d900-fe48-11ea-8522-8971f72719ec.png)

Any idea why?

**Comment by zerotypic** [comment]
Hi, I've not tested this recently, and am not really able to do so, since the main place I have Wireless@SG access is the libraries which are still closed. Comparing to my own config, I have "Anonymous identity" set to blank, and PEAP version set to "Automatic". See if that works? If you successfully retrieved a username and password pair, most likely the issue isn't with the script but with your network config.

**Comment by deearahman** [comment]
Thanks! It works!
